name: 'Ansible Deploy'
description: "Limited Deployment via Ansible"
inputs:
  aws-profile:
    description: 'AWS Profile'
    required: false
    default: 'aws'
  path:
    description: 'Ansible Repoistory Path'
    required: false
    default: 'ansible'
  options:
    description: 'Ansible Options'
    required: false
    default: ''
  playbook:
    description: 'Ansible Playbook'
    required: false
    default: 'deploy.yml'
  secret:
    description: 'Ansible Vault Secret'
    required: true
  vault-secret-file:
    description: 'Ansible Vault Secret file'
    required: false
    default: .secret/default
runs:
  using: "composite"
  steps: 
    - name: Ansible Deploy
      shell: bash
      run: | 
        /bin/ansible --version
        cd ${{ inputs.path }}
        mkdir -p $(dirname ${{ inputs.vault-secret-file }})
        echo ${{ inputs.secret }} > ${{ inputs.vault-secret-file }}
        chmod 600 ${{ inputs.vault-secret-file }}
        [ -f requirements.yml ] && ansible-galaxy collection install -r requirements.yml
        CMD='/bin/ansible-playbook ${{ inputs.options }} ${{ inputs.playbook }}'
        echo "===================================================================="
        echo $CMD
        echo "===================================================================="
        AWS_PROFILE=${{ inputs.aws-profile }} $CMD
