name: 'Ansible Vault Secret'
description: "Install Ansible Vault Secret"
inputs:
  path:
    description: 'Ansible Repoistory Path'
    required: false
    default: 'ansible'
  secret:
    description: 'Ansible Vault Secret'
    required: true
  vault-secret-file:
    description: 'Ansible Vault Secret file'
    required: false
    default: ansible/.secret/default
runs:
  using: "composite"
  steps: 
    - name: Ansible Vault Secret
      shell: bash
      run: | 
        cd ${{ inputs.path }}
        mkdir -p $(dirname ${{ inputs.vault-secret-file }})
        echo ${{ inputs.secret }} > ${{ inputs.vault-secret-file }}
        chmod 600 ${{ inputs.vault-secret-file }}
