name: 'Install Ansible'
description: "Install Ansible"
inputs:
  aws-access-key-id:
    description: 'AWS ACCESS KEY ID'
    required: true
  aws-secret-access-key:
    description: 'AWS SECRET ACCESS KEY'
    required: true
  aws-region:
    description: 'AWS region of ECR'
    required: true
    default: 'eu-west-1'
  aws-profile:
    description: 'AWS PROFILE'
    required: true
    default: 'aws'
  host-prefix:
    description: 'Hostname prefix'
    required: true
  key-file:
    description: 'SSH KEY'
    required: true
    default: 'id_rsa'
  ssh-key:
    description: 'SSH KEY'
    required: true
runs: # The new Ubuntu 24.04 Github runner installs ansible and python (albeit the latter in a strange location).
  using: "composite"
  steps: 
    - name: Ansible
      shell: bash
      run: | 
        curl -sL https://ports.ubuntu.com/pool/universe/a/ansible-core/ansible-core_2.18.1-4ubuntu1_all.deb > /tmp/ansible.deb
        sudo apt-get install /tmp/ansible.deb
        /bin/ansible --version

    - name: Python Modules
      shell: bash
      run: | 
        sudo apt-get install python3-docker python3-boto3 python3-botocore
        dpkg -l | grep python3

    - name: AWS Credentials
      shell: bash
      run: | 
        mkdir ~/.aws
        echo "[${{ inputs.aws-profile }}]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key-id}}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-access-key }}" >> ~/.aws/credentials
        echo "region=${{ inputs.aws-region }}" >> ~/.aws/credentials
        chmod 600 ~/.aws/credentials

    - name: SSH Configuration
      id: ssh
      shell: bash
      run: | 
        [ ! -d ~/.ssh ] && mkdir ~/.ssh
        echo "IdentityFile ~/.ssh/${{ inputs.key-file }}" > ~/.ssh/config
        echo "User ec2-user" >> ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        echo "Host ${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
        echo "  hostname %h.epimorphics.net" >> ~/.ssh/config
        echo "Host ${{ inputs.host-prefix }}-* ${{ inputs.host-prefix }}_* 10.* !${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
        echo "  ProxyJump ${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
