name: 'Install Ansible'
description: "Install Ansible"
inputs:
  aws-access-key-id:
    description: 'AWS ACCESS KEY ID'
    required: true
  aws-secret-access-key:
    description: 'AWS SECRET ACCESS KEY'
    required: true
  aws-region:
    description: 'AWS region of ECR'
    required: false
    default: 'eu-west-1'
  aws-profile:
    description: 'AWS PROFILE'
    required: false
    default: 'aws'
  host-prefix:
    description: 'Hostname prefix'
    required: true
  key-file:
    description: 'SSH KEY'
    required: false
    default: 'id_rsa'
  ssh-key:
    description: 'SSH KEY'
    required: true
runs:
  using: "composite"
  steps: 
    - name: Ansible
      shell: bash
      run: | 
        sudo apt-add-repository ppa:ansible/ansible
        sudo apt update
        sudo apt install ansible
        /bin/ansible --version

    - name: Python Modules
      shell: bash
      run: | 
        python -m pip install --upgrade pip
        pip install botocore boto boto3

    - name: AWS Credentials
      shell: bash
      run: | 
        mkdir ~/.aws
        echo "[${{ inputs.aws-profile }}]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ inputs.aws-access-key-id}}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ inputs.aws-secret-access-key }}" >> ~/.aws/credentials
        echo "region=${{ inputs.aws-region }}" >> ~/.aws/credentials
        chmod 600 ~/.aws/credentials

    - name: SSH Configuration
      id: ssh
      shell: bash
      run: | 
        [ ! -d ~/.ssh ] && mkdir ~/.ssh
        echo "IdentityFile ~/.ssh/${{ inputs.key-file }}" > ~/.ssh/config
        echo "User ec2-user" >> ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        echo "Host ${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
        echo "  hostname %h.epimorphics.net" >> ~/.ssh/config
        echo "Host ${{ inputs.host-prefix }}-* ${{ inputs.host-prefix }}_* 10.* !${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
        echo "  ProxyJump ${{ inputs.host-prefix }}-bastion" >> ~/.ssh/config
#       echo "${{ inputs.ssh-key }}" > ~/.ssh/${{ inputs.key-file }}
